export const images = {
	aws: "/aws.svg",
	bem: "/bem.svg",
	csharp: "/csharp.svg",
	cplus: "/cplus.svg",
	docker: "/docker.svg",
	figma: "/figma.svg",
	github: "/github.svg",
	java: "/java.svg",
	javascript: "/javascript.svg",
	leetcode: "/leetcode.svg",
	link: "/link.svg",
	linkedin: "/linkedin.svg",
	nextjs: "/nextjs.svg",
	node: "/node.svg",
	potrait: "/portait.png",
	python: "/python.svg",
	react: "/react.svg",
	redux: "/redux.svg",
	sass: "/sass.svg",
	tailwind: "/tailwind.svg",
	typescript: "/typescript.svg",
	unity: "/unity.svg",
	vercel: "/vercel.svg",
	vite: "/vite.svg",
	w3c: "/W3Ccheck.svg",
};
